/*
 * This file is generated by jOOQ.
 */
package io.effective;


import io.effective.tables.CmsAccessKey;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>smartops</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index CMS_ACCESS_KEY_CMS_ACCESS_KEY_ACCESS_KEY_ID_UINDEX = Indexes0.CMS_ACCESS_KEY_CMS_ACCESS_KEY_ACCESS_KEY_ID_UINDEX;
    public static final Index CMS_ACCESS_KEY_CMS_ACCESS_KEY_SRN_UINDEX = Indexes0.CMS_ACCESS_KEY_CMS_ACCESS_KEY_SRN_UINDEX;
    public static final Index CMS_ACCESS_KEY_PRIMARY = Indexes0.CMS_ACCESS_KEY_PRIMARY;
    public static final Index CMS_ACCESS_KEY_SYS_CLOUD_ACCESS_ID_UINDEX = Indexes0.CMS_ACCESS_KEY_SYS_CLOUD_ACCESS_ID_UINDEX;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index CMS_ACCESS_KEY_CMS_ACCESS_KEY_ACCESS_KEY_ID_UINDEX = Internal.createIndex("cms_access_key_access_key_id_uindex", CmsAccessKey.CMS_ACCESS_KEY, new OrderField[] { CmsAccessKey.CMS_ACCESS_KEY.ACCESS_KEY_ID }, true);
        public static Index CMS_ACCESS_KEY_CMS_ACCESS_KEY_SRN_UINDEX = Internal.createIndex("cms_access_key_srn_uindex", CmsAccessKey.CMS_ACCESS_KEY, new OrderField[] { CmsAccessKey.CMS_ACCESS_KEY.SRN }, true);
        public static Index CMS_ACCESS_KEY_PRIMARY = Internal.createIndex("PRIMARY", CmsAccessKey.CMS_ACCESS_KEY, new OrderField[] { CmsAccessKey.CMS_ACCESS_KEY.ID }, true);
        public static Index CMS_ACCESS_KEY_SYS_CLOUD_ACCESS_ID_UINDEX = Internal.createIndex("sys_cloud_access_id_uindex", CmsAccessKey.CMS_ACCESS_KEY, new OrderField[] { CmsAccessKey.CMS_ACCESS_KEY.ID }, true);
    }
}
