/*
 * This file is generated by jOOQ.
 */
package io.effective;


import io.effective.tables.CmsAccessKey;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in smartops
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>smartops.cms_access_key</code>.
     */
    public static final CmsAccessKey CMS_ACCESS_KEY = io.effective.tables.CmsAccessKey.CMS_ACCESS_KEY;
}
