/*
 * This file is generated by jOOQ.
 */
package io.effective.tables.records;


import io.effective.tables.CmsAccessKey;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record17;
import org.jooq.Row17;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CmsAccessKeyRecord extends UpdatableRecordImpl<CmsAccessKeyRecord> implements Record17<Integer, String, String, String, Long, String, String, Boolean, String, String, Timestamp, Boolean, Timestamp, String, Timestamp, String, Boolean> {

    private static final long serialVersionUID = 523135790;

    /**
     * Setter for <code>smartops.cms_access_key.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>smartops.cms_access_key.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>smartops.cms_access_key.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>smartops.cms_access_key.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>smartops.cms_access_key.corp</code>.
     */
    public void setCorp(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>smartops.cms_access_key.corp</code>.
     */
    public String getCorp() {
        return (String) get(2);
    }

    /**
     * Setter for <code>smartops.cms_access_key.srn</code>.
     */
    public void setSrn(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>smartops.cms_access_key.srn</code>.
     */
    public String getSrn() {
        return (String) get(3);
    }

    /**
     * Setter for <code>smartops.cms_access_key.account_id</code>.
     */
    public void setAccountId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>smartops.cms_access_key.account_id</code>.
     */
    public Long getAccountId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>smartops.cms_access_key.access_key_id</code>.
     */
    public void setAccessKeyId(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>smartops.cms_access_key.access_key_id</code>.
     */
    public String getAccessKeyId() {
        return (String) get(5);
    }

    /**
     * Setter for <code>smartops.cms_access_key.secret_access_key</code>.
     */
    public void setSecretAccessKey(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>smartops.cms_access_key.secret_access_key</code>.
     */
    public String getSecretAccessKey() {
        return (String) get(6);
    }

    /**
     * Setter for <code>smartops.cms_access_key.sync_enabled</code>.
     */
    public void setSyncEnabled(Boolean value) {
        set(7, value);
    }

    /**
     * Getter for <code>smartops.cms_access_key.sync_enabled</code>.
     */
    public Boolean getSyncEnabled() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>smartops.cms_access_key.sync_state</code>.
     */
    public void setSyncState(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>smartops.cms_access_key.sync_state</code>.
     */
    public String getSyncState() {
        return (String) get(8);
    }

    /**
     * Setter for <code>smartops.cms_access_key.error</code>.
     */
    public void setError(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>smartops.cms_access_key.error</code>.
     */
    public String getError() {
        return (String) get(9);
    }

    /**
     * Setter for <code>smartops.cms_access_key.last_sync_at</code>.
     */
    public void setLastSyncAt(Timestamp value) {
        set(10, value);
    }

    /**
     * Getter for <code>smartops.cms_access_key.last_sync_at</code>.
     */
    public Timestamp getLastSyncAt() {
        return (Timestamp) get(10);
    }

    /**
     * Setter for <code>smartops.cms_access_key.available</code>.
     */
    public void setAvailable(Boolean value) {
        set(11, value);
    }

    /**
     * Getter for <code>smartops.cms_access_key.available</code>.
     */
    public Boolean getAvailable() {
        return (Boolean) get(11);
    }

    /**
     * Setter for <code>smartops.cms_access_key.created_at</code>.
     */
    public void setCreatedAt(Timestamp value) {
        set(12, value);
    }

    /**
     * Getter for <code>smartops.cms_access_key.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(12);
    }

    /**
     * Setter for <code>smartops.cms_access_key.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>smartops.cms_access_key.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(13);
    }

    /**
     * Setter for <code>smartops.cms_access_key.updated_at</code>.
     */
    public void setUpdatedAt(Timestamp value) {
        set(14, value);
    }

    /**
     * Getter for <code>smartops.cms_access_key.updated_at</code>.
     */
    public Timestamp getUpdatedAt() {
        return (Timestamp) get(14);
    }

    /**
     * Setter for <code>smartops.cms_access_key.updated_by</code>.
     */
    public void setUpdatedBy(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>smartops.cms_access_key.updated_by</code>.
     */
    public String getUpdatedBy() {
        return (String) get(15);
    }

    /**
     * Setter for <code>smartops.cms_access_key.deleted</code>.
     */
    public void setDeleted(Boolean value) {
        set(16, value);
    }

    /**
     * Getter for <code>smartops.cms_access_key.deleted</code>.
     */
    public Boolean getDeleted() {
        return (Boolean) get(16);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record17 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row17<Integer, String, String, String, Long, String, String, Boolean, String, String, Timestamp, Boolean, Timestamp, String, Timestamp, String, Boolean> fieldsRow() {
        return (Row17) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row17<Integer, String, String, String, Long, String, String, Boolean, String, String, Timestamp, Boolean, Timestamp, String, Timestamp, String, Boolean> valuesRow() {
        return (Row17) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return CmsAccessKey.CMS_ACCESS_KEY.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return CmsAccessKey.CMS_ACCESS_KEY.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return CmsAccessKey.CMS_ACCESS_KEY.CORP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return CmsAccessKey.CMS_ACCESS_KEY.SRN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return CmsAccessKey.CMS_ACCESS_KEY.ACCOUNT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return CmsAccessKey.CMS_ACCESS_KEY.ACCESS_KEY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return CmsAccessKey.CMS_ACCESS_KEY.SECRET_ACCESS_KEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field8() {
        return CmsAccessKey.CMS_ACCESS_KEY.SYNC_ENABLED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return CmsAccessKey.CMS_ACCESS_KEY.SYNC_STATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return CmsAccessKey.CMS_ACCESS_KEY.ERROR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field11() {
        return CmsAccessKey.CMS_ACCESS_KEY.LAST_SYNC_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field12() {
        return CmsAccessKey.CMS_ACCESS_KEY.AVAILABLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field13() {
        return CmsAccessKey.CMS_ACCESS_KEY.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return CmsAccessKey.CMS_ACCESS_KEY.CREATED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field15() {
        return CmsAccessKey.CMS_ACCESS_KEY.UPDATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field16() {
        return CmsAccessKey.CMS_ACCESS_KEY.UPDATED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field17() {
        return CmsAccessKey.CMS_ACCESS_KEY.DELETED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getCorp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getSrn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component5() {
        return getAccountId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getAccessKeyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getSecretAccessKey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component8() {
        return getSyncEnabled();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getSyncState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getError();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component11() {
        return getLastSyncAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component12() {
        return getAvailable();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component13() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component14() {
        return getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component15() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component16() {
        return getUpdatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component17() {
        return getDeleted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCorp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getSrn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getAccountId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getAccessKeyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getSecretAccessKey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value8() {
        return getSyncEnabled();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getSyncState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getError();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value11() {
        return getLastSyncAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value12() {
        return getAvailable();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value13() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value15() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value16() {
        return getUpdatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value17() {
        return getDeleted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CmsAccessKeyRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CmsAccessKeyRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CmsAccessKeyRecord value3(String value) {
        setCorp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CmsAccessKeyRecord value4(String value) {
        setSrn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CmsAccessKeyRecord value5(Long value) {
        setAccountId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CmsAccessKeyRecord value6(String value) {
        setAccessKeyId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CmsAccessKeyRecord value7(String value) {
        setSecretAccessKey(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CmsAccessKeyRecord value8(Boolean value) {
        setSyncEnabled(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CmsAccessKeyRecord value9(String value) {
        setSyncState(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CmsAccessKeyRecord value10(String value) {
        setError(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CmsAccessKeyRecord value11(Timestamp value) {
        setLastSyncAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CmsAccessKeyRecord value12(Boolean value) {
        setAvailable(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CmsAccessKeyRecord value13(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CmsAccessKeyRecord value14(String value) {
        setCreatedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CmsAccessKeyRecord value15(Timestamp value) {
        setUpdatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CmsAccessKeyRecord value16(String value) {
        setUpdatedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CmsAccessKeyRecord value17(Boolean value) {
        setDeleted(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CmsAccessKeyRecord values(Integer value1, String value2, String value3, String value4, Long value5, String value6, String value7, Boolean value8, String value9, String value10, Timestamp value11, Boolean value12, Timestamp value13, String value14, Timestamp value15, String value16, Boolean value17) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CmsAccessKeyRecord
     */
    public CmsAccessKeyRecord() {
        super(CmsAccessKey.CMS_ACCESS_KEY);
    }

    /**
     * Create a detached, initialised CmsAccessKeyRecord
     */
    public CmsAccessKeyRecord(Integer id, String name, String corp, String srn, Long accountId, String accessKeyId, String secretAccessKey, Boolean syncEnabled, String syncState, String error, Timestamp lastSyncAt, Boolean available, Timestamp createdAt, String createdBy, Timestamp updatedAt, String updatedBy, Boolean deleted) {
        super(CmsAccessKey.CMS_ACCESS_KEY);

        set(0, id);
        set(1, name);
        set(2, corp);
        set(3, srn);
        set(4, accountId);
        set(5, accessKeyId);
        set(6, secretAccessKey);
        set(7, syncEnabled);
        set(8, syncState);
        set(9, error);
        set(10, lastSyncAt);
        set(11, available);
        set(12, createdAt);
        set(13, createdBy);
        set(14, updatedAt);
        set(15, updatedBy);
        set(16, deleted);
    }
}
