package io.effective.mapper;

import io.effective.model.AmsAccount;
import io.effective.model.AmsAccountExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Mapper
@Component
public interface AmsAccountMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ams_account
	 * @mbg.generated
	 */
	long countByExample(AmsAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ams_account
	 * @mbg.generated
	 */
	int deleteByExample(AmsAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ams_account
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ams_account
	 * @mbg.generated
	 */
	int insert(AmsAccount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ams_account
	 * @mbg.generated
	 */
	int insertSelective(AmsAccount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ams_account
	 * @mbg.generated
	 */
	List<AmsAccount> selectByExample(AmsAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ams_account
	 * @mbg.generated
	 */
	AmsAccount selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ams_account
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") AmsAccount record, @Param("example") AmsAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ams_account
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") AmsAccount record, @Param("example") AmsAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ams_account
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(AmsAccount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ams_account
	 * @mbg.generated
	 */
	int updateByPrimaryKey(AmsAccount record);
}